name: "Custom Snyk Action"
description: "Run a Snyk Monitor requiring an org name"
inputs:
  organization:
    description: "Snyk Organization ID or Name"
    required: true
  arguments:
    description: "Extra Snyk CLI options"
    required: false
runs:
  using: "composite"
  steps:
    - uses: snyk/actions/setup@master
    - id: run-snyk-test
      run: snyk monitor --org=${{ inputs.organization }} ${{ inputs.arguments }}
      shell: bash
