name: "Custom Snyk Action"
description: "Run a Snyk Monitor requiring an org name"
inputs:
  organization:
    description: "Snyk Organization ID or Name"
    required: true
  snyk-version:
    description: "Which Snyk version to install"
    default: latest
  arguments:
    description: "Extra Snyk CLI options"
    required: false
runs:
  using: "composite"
  steps:
    - id: install-snyk
      run: ${{ github.action_path }}/install_posix.sh ${{ inputs.snyk-version }} ${{ runner.os }}
      shell: bash
    - id: run-snyk-test
      run: snyk monitor --org=${{ inputs.organization }} ${{ inputs.arguments }}
      shell: bash
