name: "Custom Snyk Action"
description: "Run a Snyk Monitor requiring an org name"
inputs:
  organization:
    description: "Snyk Organization ID or Name"
    required: true
  arguments:
    description: "Extra Snyk CLI options"
    required: false
runs:
  using: "composite"
  steps:
    - id: install-snyk
      run: ${{ github.action_path }}/install_posix.sh
      shell: bash
    - id: run-snyk-test
      run: ${{ steps.vars.outputs.snyk_path }} monitor --org=${{ inputs.organization }} ${{ inputs.arguments }}
      shell: bash
