name: Checkout and Run Snyk

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run a Snyk Monitor
    steps:
      - uses: actions/checkout@v2
      - id: snyk-test
        uses: ./.github/actions/custom-snyk
        with:
          organization: angrydome
          arguments: --severity=critical
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
